version: '3.7'
services:
    nginx:
        image: nginx:latest
        container_name: nginx
        working_dir: /etc/nginx
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www/app
            - ./deployment/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./deployment/nginx/sites:/etc/nginx/conf.d
            - ./deployment/logs/nginx:/var/log/nginx
        depends_on:
            - app
        networks:
            - backend

    app:
        build:
            context: ./deployment/php
            dockerfile: Dockerfile
        image: backend
        container_name: app
        working_dir: /var/www/app
        volumes:
            - .:/var/www/app
        depends_on:
            - postgres_db
        networks:
            - backend

    postgres_db:
        image: postgres:14
        container_name: postgres_db
        restart: unless-stopped
        tty: true
        ports:
            - '5432:5432'
        environment:
            - POSTGRES_DB=${DB_DATABASE}
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        volumes:
            - './deployment/volumes/postgres:/var/lib/postgresql/data'
        networks:
            - backend


    pgadmin:
        image: dpage/pgadmin4
        container_name: pgAdmin
        environment:
            - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
            - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
        ports:
            - "5050:80"
        depends_on:
            - postgres_db
        networks:
            - backend

networks:
    backend:
