version: '3.7'
services:
    nginx:
        image: nginx:latest
        container_name: nginx_99
        working_dir: /etc/nginx
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www/app
            - ./deployment/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./deployment/nginx/sites:/etc/nginx/conf.d
            - ./deployment/logs/nginx:/var/log/nginx
        networks:
            - backend
        depends_on:
            - php

    php:
        build:
            context: ./deployment/php
            dockerfile: Dockerfile
#            args:
#                ENABLE_XDEBUG: ${DOCKER_ENABLE_XDEBUG}

        image: backend
        container_name: app_99
        working_dir: /var/www/app
        volumes:
            - .:/var/www/app
        networks:
            - backend
        depends_on:
            mysql:
                condition: service_healthy

    supervisor:
        build:
            context: ./deployment/supervisor
            dockerfile: Dockerfile
            args:
                ENABLE_SUPERVISOR: ${DOCKER_ENABLE_SUPERVISOR}
        working_dir: /etc/supervisor
        volumes:
            - .:/var/www/app
            - ./deployment/logs/supervisor:/var/log/supervisor
        networks:
            - backend
        depends_on:
            - php

    mysql:
        image: mysql
        container_name: db_99
        restart: unless-stopped
        tty: true
        ports:
            - '3366:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - './deployment/volumes/mysql:/var/lib/mysql'
        healthcheck:
            test: [ "CMD", "mysql", "-u" , '${DB_USERNAME}', '-p${DB_PASSWORD}' ]
            timeout: 2s
            interval: 5s
            retries: 5
        networks:
            - backend
networks:
    backend:
